### ISSUE TITLE
Licence

### ISSUE THREAD

**Issue by colms** [mmmaat/libgammatone#1]
I was wondering if you would consider a less restrictive licence, such as MIT or BSD. I want to use libgammatone but I don't want my library to become GNU as I'm hoping to have it used in many diffrent environments.

Thanks

**Comment by mmmaat** [comment]
Hi Colms,

Sorry for being so long to answer... I do not consider changing license, GPL is just what I need for this project.

Mathieu

**Comment by colms** [comment]
No problem. After I wrote it I thought I probably shouldn't have. Sorry about that.
